### ISSUE TITLE
Activesupport 2.3.14

### ISSUE THREAD

**Issue by AlvaroOlivencia** [Miniand/zooz-ruby#3]
Hi,
I would like to use this gem but it depends on activesupport 3.2.0, my rails version is 2.3.14.
When I run bundle I get:

> Bundler could not find compatible versions for gem "activesupport":
>  In Gemfile:
>   zooz (= 1.0.2) ruby depends on
>      activesupport (~> 3.2.0) ruby
> 
>    rails (= 2.3.14) ruby depends on
>      activesupport (2.3.14)

Could you please tell me how could I make your gem work with this version of rails (Activesupport) ?
Thanks !

**Comment by beefsack** [comment]
Hello @AlvaroOlivencia, sorry about my delay in getting back to you,

Unfortunately, the gem was developed using the newer version of AS, and I don't really have time to update it.

If you are interested to fork and try yourself though, I'd suggest just changing the Gemfile to require an older version of AS and seeing if it works as it may just be fine out of the box.
